name: Female-Gender-Mod-Plugin
version: '${project.version}'
main: dbrighthd.wildfiregendermodplugin.GenderModPlugin
api-version: '1.21'
folia-supported: true
authors: [ 'dbrighthd', 'Stigstille', 'winnpixie', 'BF-GO' ]
